networks:
    backend:
    frontend:
services:
    backend:
        build: Back-end
        container_name: backend
        ports:
            - "9091:9091"
        restart: always
        environment:
            - DATABASE_HOST=database
            - DATABASE_USER=adminUser
            - DATABASE_PASSWORD=password
            - DATABASE_NAME=mysql-refun
            - DATABASE_PORT=3306    
        depends_on:
            - database
        networks:
            - backend
            - frontend
    frontend:
        build: Front-end
        container_name: frontend
        ports:
            - "9090:9090"
        restart: always
        depends_on:
            - backend
        networks:
            - frontend  
    database:
        container_name: database
        image: mysql/mysql-server:8.0.24
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=refun123
            - MYSQL_DATABASE=mysql-refun
            - MYSQL_USER=user
        ports:
            - "3306:3306"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - backend  
