services:
    backend:
        build: Back-end
        container_name: backend
        restart: on-failure
        environment:
            - DATABASE_HOST=database
            - DATABASE_USER=adminUser
            - DATABASE_PASSWORD=password
            - DATABASE_NAME=mysql-refun
            - DATABASE_PORT=3306    
        depends_on:
            - database
    frontend:
        build: Front-end
        container_name: frontend
        depends_on:
            - backend
    database:
        container_name: database
        image: mysql/mysql-server:8.0.24
        restart: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD=refun123
            - MYSQL_DATABASE=mysql-refun
            - MYSQL_USER=user
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    reverse-poxy:
        image: nginx
        container_name: reverse-poxy
        depends_on:
            - frontend
            - backend
            - database
        volumes: 
            - ./poxy/nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - "80:80"
    