version: '3.7'
services:
    backend:
        build: Back-end
        container_name: backend
        ports:
            - "9091:9091"
        restart: always
    frontend:
        build: Front-end
        container_name: frontend
        ports:
            - 9090:9090
        restart: always
        depends_on:
            - backend