networks:
    backend:
    frontend:
services:
    backend:
        build: Back-end
        container_name: backend
        ports:
            - "9091:9091"
        restart: on-failure
        environment:
            - DATABASE_HOST=database
            - DATABASE_USER=adminUser
            - DATABASE_PASSWORD=password
            - DATABASE_NAME=mysql-refun
            - DATABASE_PORT=3306    
        depends_on:
            - database
        networks:
            - backend
            - frontend
    frontend:
        build: Front-end
        container_name: frontend
        ports:
            - "9090:80"
        restart: on-failure
        depends_on:
            - backend
        networks:
            - frontend  
    database:
        container_name: database
        image: mysql/mysql-server:8.0.24
        restart: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD=refun123
            - MYSQL_DATABASE=mysql-refun
            - MYSQL_USER=user
        ports:
            - "3306:3306"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - backend  
    reverse-poxy:
        image: nginx:1.17.10
        container_name: reverse-poxy
        depends_on:
            -frontend
            -backend
            -database
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports: 
            -"80:80"
    