version: '3.7'
services:
    backend:
        build: Back-end
        container_name: backend
        ports:
            - "9091:9091"
        restart: always
    frontend:
        build: Front-end
        container_name: frontend
        ports:
            - 9090:9090
        restart: always
        depends_on:
            - backend
    database:
        image: mysql:8.0.24
        ports: 
            - "3306:3306"
        restart: always
        environment:
            MYSQL_DATABASE: mysql-refun
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: refun123
          volumes:
            - db-data:/var/lib/mysql
