services:
    backend:
        build: Back-end
        container_name: backend
        ports:
            - "9091:9091"
        restart: always
    frontend:
        build: Front-end
        container_name: frontend
        ports:
            - "9090:9090"
        restart: always
        depends_on:
            - backend
    db:
        image: mysql:5.7
        ports:
        - "3306:3306"
        restart: always
        environment:
        MYSQL_DATABASE: polls
        MYSQL_USER: callicoder
        MYSQL_PASSWORD: callicoder
        MYSQL_ROOT_PASSWORD: root
        volumes:
        - db-data:/var/lib/mysql
        networks:
        - backend  
    
    # Volumes
volumes:
    db-data: