services:
    backend:
        build: Back-end
        container_name: backend
        ports:
            - "9091:9091"
        restart: always
    frontend:
        build: Front-end
        container_name: frontend
        ports:
            - "9090:9090"
        restart: always
        depends_on:
            - backend
    db:
        container_name: database2
        image: mysql/mysql-server:8.0.24
        restart: always
        environment:
            MYSQL_USER: 'user'
            MYSQL_ROOT_PASSWORD: 'refun123'
            MYSQL_DATABASE: mysql-refun
        ports:
            - "3307:3307"
        command:
        volumes:
            - "./db.sql:/var/lib/mysql"
